# Generated by Django 3.0.6 on 2020-07-27 17:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('article_content', ckeditor.fields.RichTextField()),
                ('references', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='Add the subject you want to create articles about.', max_length=300)),
                ('subject_description', ckeditor.fields.RichTextField()),
                ('branch', models.CharField(choices=[('CIVIL', 'Civil Engineering'), ('MECH', 'Mechanical Engineering'), ('ECE', 'Electronics & Communication Engineering')], default='CIVIL', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(default='user@Engineers.com', max_length=200)),
                ('author', models.TextField(max_length=300)),
                ('comment_content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=300)),
                ('chapter_number', models.IntegerField(default=0)),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='blog.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='chapter_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Chapter'),
        ),
        migrations.AddField(
            model_name='article',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Subject'),
        ),
    ]
